apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fcarbah-com-tls
spec:
  secretName: fcarbah-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fcarbah.com
  dnsNames: 
    - fcarbah.com 
    - www.fcarbah.com 
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fcarbah.com
          - www.fcarbah.com