apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - fcarbah.com
        - www.fcarbah.com
      secretName: fcarbah-com
  rules:
    - host: fcarbah.com
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: musicapp-cluster-ip-service
              servicePort: 3000
    - host: www.fcarbah.com
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: musicapp-cluster-ip-service
              servicePort: 3000